name: "Publish Build to Artifactory"
on:
  workflow_dispatch:

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:
           JF_URL: ${{ secrets.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           JFROG_CLI_BUILD_NAME: ${{ vars.BUILD_NAME }}
           JFROG_CLI_BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}

       - name: Set CLI Config
         run: jf pip-config --global=true --repo-resolve=${{ vars.JF_PYPI_REPO }}

       - name: Install Deps
         run: jf pip install .

       - name: Install pipenv
         run: jf pip install pipenv

       - name: Scan the source code
         run: jf audit --project ${{ vars.JF_PROJECT }}

       - name: Package the project
         run: python setup.py sdist bdist_wheel

       - name: Scan the binaries
         run: jf scan "dist/*" --project ${{ vars.JF_PROJECT }}

       - name: Publish
         run: jf rt upload dist/ ${{ vars.JF_PYPI_REPO }}/

       - name: Publish Build info With JFrog CLI
         env:
           JFROG_CLI_BUILD_NAME: ${{ vars.BUILD_NAME }}
           JFROG_CLI_BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}
         run: |
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish --detailed-summary --project ${{ vars.JF_PROJECT }}

       - name: Install Dep
         run: jf pip install metarng

